# Build configuration for Railway
[phases.setup]
nixPkgs = ['nodejs', 'npm', 'python39', 'postgresql']

[phases.install]
cmds = [
    "cd backend && pip install -r requirements.txt",
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    "cd frontend && npm run build"
]

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
